#ifndef _APL79_FON_H
#define _APL79_FON_H

// #define C_UP_SHOE				"\x??"
#define C_DIAERESIS			"\xa1"
#define	C_OVERBAR				"\xa2"
#define	C_LEFT_CARET		"\x3c"
#define	C_LT_EQUAL			"\xa4"
#define	C_EQUAL 				"\x3d"
#define	C_GT_EQUAL			"\xa6"
#define	C_RIGHT_CARET		"\x3e"
#define	C_NOT_EQUAL			"\xa8"
#define	C_DOWN_CARET		"\xa9"
#define	C_UP_CARET			"\x5e"
#define	C_MULTIPLY			"\xab"
#define	C_DIVIDE				"\xdf"
#define	C_QUERY 				"\x3f"
#define	C_EPSILON				"\xc5"
#define C_RHO	    			"\xd2"
#define	C_TILDE	    		"\x7e"
#define	C_UP_ARROW			"\xd9"
#define	C_DOWN_ARROW		"\xd5"
#define	C_IOTA					"\xc9"
#define C_CIRCLE				"\xcf"
#define C_STAR					"\x2a"
#define	C_LEFT_ARROW		"\xfb"
#define	C_RIGHT_ARROW		"\xfd"
#define	C_UP_STILE			"\xd3"
#define	C_DOWN_STILE		"\xc4"
#define	C_UNDERBAR			"\x5f"
#define	C_DEL						"\xc7"
#define	C_DELTA					"\xc8"
#define C_JOT						"\xca"
#define	C_QUOTE					"\x27"
#define	C_QUAD					"\xcc"
#define	C_RIGHT_SHOE		"\xc8"
#define	C_UP_SHOE_JOT		"\xe3"
#define	C_UP_TACK				"\xc2"
#define C_DOWN_TACK			"\xce"
#define C_STILE					"\x7c"
#define	C_SLASH					"\x2f"
#define	C_BACKSLASH			"\x5c"
#define C_QUOTE_DOT			"\x21"
#define	C_IBEAM					"\xe0"
#define	C_COMMA_BAR			"\xac"
#define	C_QUAD_DIVIDE		"\xad"
#define C_DIAERESIS_TILDE	"\xae"
#define	C_SLASH_BAR	  	"\xaf"
#define	C_DOWN_CARET_TILDE	"\xb9"
#define	C_UP_CARET_TILDE	"\xb0"
#define	C_EQUAL_UNDERBAR	"\xbd"
#define	C_BACKSLASH_BAR	"\xdc"
#define	C_CIRCLE_BAR		"\xe1"
#define	C_UP_TACK_JOT		"\xe2"
#define	C_DEL_TILDE			"\xe6"
#define C_DEL_STILE			"\xe7"
#define	C_DELTA_STILE		"\xe8"
#define	C_QUOTE_QUAD		"\xec"
#define	C_DOWN_TACK_JOT	"\xee"
#define	C_CIRCLE_STAR		"\xf0"
#define	C_CIRCLE_BACKSLASH  "\xf4"
#define	C_CIRCLE_STILE	"\xf7"
#define	C_DIAMOND				"\xfe"
#define	C_PLUS					"\x2b"
#define	C_BAR						"\x2d"
#define	C_COMMA					"\x2c"
#define	C_SEMICOLON			"\x3b"
#define	C_DOT						"\x2e"
#define	C_COLON					"\x3a"

// #define C_ALPHA					"\xb8"
// #define C_LEFT_SHOE			"\x9b"
// #define C_DOWN_SHOE			"\x9e"
// #define C_DELTA_UNDERBAR	"\x8f"
// #define C_EPSILON_UNDERBAR  "\xba"
// #define C_OMEGA					"\xbe"
// #define C_SQUAD					"\xa6"
// #define C_LOGAMMA				"\xbf"
// #define C_YEN						"\x80"
// #define C_CIRCLE_DIAERESIS	"\xf6"
// #define C_FONT					"\xa3"
// #define C_LEFT_TACK			"\x81"
// #define C_RIGHT_TACK		"\xa4"
// #define C_DIAERESIS_JOT	"\xf0"
// #define C_CENT					"\xa2"

#endif /* _APL79_FON_H */
