#ifndef _SOCKET_H_
#define	_SOCKET_H_

#include <apluswin32.h>

#define	EINPROGRESS				WSAEINPROGRESS
#define	EISCONN						WSAEISCONN

#define	EWOULDBLOCK				WSAEWOULDBLOCK
#define	EALREADY					WSAEALREADY
#define	ENOTSOCK					WSAENOTSOCK
#define	EDESTADDRREQ			WSAEDESTADDRREQ
#define	EMSGSIZE					WSAEMSGSIZE
#define	EPROTOTYPE				WSAEPROTOTYPE
#define	ENOPROTOOPT				WSAENOPROTOOPT
#define	EPROTONOSUPPORT		WSAEPROTONOSUPPORT
#define	ESOCKTNOSUPPORT		WSAESOCKTNOSUPPORT
#define	EOPNOTSUPP				WSAEOPNOTSUPP
#define	EPFNOSUPPORT			WSAEPFNOSUPPORT
#define	EAFNOSUPPORT			WSAEAFNOSUPPORT
#define	EADDRINUSE				WSAEADDRINUSE
#define	EADDRNOTAVAIL			WSAEADDRNOTAVAIL
#define	ENETDOWN					WSAENETDOWN
#define	ENETUNREACH				WSAENETUNREACH
#define	ENETRESET					WSAENETRESET
#define	ECONNABORTED			WSAECONNABORTED
#define	ECONNRESET				WSAECONNRESET
#define	ENOBUFS						WSAENOBUFS
#define	ENOTCONN					WSAENOTCONN
#define	ESHUTDOWN					WSAESHUTDOWN
#define	ETOOMANYREFS			WSAETOOMANYREFS
#define	ETIMEDOUT					WSAETIMEDOUT
#define	ECONNREFUSED			WSAECONNREFUSED
#define	ELOOP							WSAELOOP
#define	EHOSTDOWN					WSAEHOSTDOWN
#define	EHOSTUNREACH			WSAEHOSTUNREACH
#define	EUSERS						WSAEUSERS
#define	ESTALE						WSAESTALE
#define	EREMOTE						WSAEREMOTE

#endif
